# Generated by Django 2.0 on 2019-12-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(default='')),
                ('gender', models.BooleanField(default=True)),
                ('phone', models.CharField(default='', max_length=11)),
                ('salary', models.DecimalField(decimal_places=2, default=2480, max_digits=8)),
                ('department', models.CharField(default='', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'staffinfo',
            },
        ),
    ]
