# Generated by Django 2.0 on 2020-03-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pphone', models.CharField(default='', max_length=11)),
                ('pemail', models.CharField(max_length=50)),
                ('padderss', models.CharField(default='', max_length=100)),
                ('pbeizhu', models.CharField(default='', max_length=200)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=20)),
                ('ppicture', models.CharField(max_length=20)),
                ('pintro', models.CharField(max_length=200)),
                ('pcontent', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
